### ISSUE TITLE
harambe sayfası ve our project sayfası

### ISSUE THREAD

**Issue by alperenkirimer** [HarambeSoft/harambe-web-site#10]
açın da doldurmaya başlayalım yavaştan

**Comment by alperenkirimer** [comment]
harambeyi doldurdum biraz, bakın ekleme çıkarma falan yapacaksanız

**Comment by sbozturk** [comment]
Harambe için yeterince bilgi girildi project sayfasına yönelim bence artık. Title'ı güncelleyerek başladım. Diğer istenenleri de issues şeklinde yapalım.
