### ISSUE TITLE
Proje ismi ve sloganı

### ISSUE THREAD

**Issue by isamert** [HarambeSoft/harambe-web-site#11]
İsim `+1` olarak seçildiğine göre slogan kaldı geriye. Onu da bi şeyedersek proje sayfasını tamamlamak lazım.

**Comment by isamert** [comment]
Konuşulanlar şunlardı:
- Get or give opinions
- Get opinions, from neighbors
- You decide
- Sharing improved
- Getting answers, the right way
- Sharing is caring
- Dont be so shy
- The app that cares about your opinion
- The app you can +1
- The app for attention whores
- The app you can trust

**Comment by keremcodes** [comment]
"Get Opinions From Neighbors" güzel.
