### ISSUE TITLE
Project Definition

### ISSUE THREAD

**Issue by sbozturk** [HarambeSoft/harambe-web-site#13]
Our project is an android app that will help all people to decide about anything. There will not be any indecision. You can create a poll and ask whatever you want to who is near you.

Eklemek istediğiniz şeyler varsa ekleyin.

**Comment by Alpccelik** [comment]
Açıklama için yeterli

**Comment by gizemfitoz** [comment]
Bence de güzel bu kadarı

**Comment by alperenkirimer** [comment]
Our project is a location-based android application, that simply aims to aid people who may help each other. It allows users to be a "plus-one" in order to end an indecision. Users will be able to create polls or participate in other polls created by other people around them.

**Comment by sbozturk** [comment]
Siteye eklendi
