### ISSUE TITLE
Project Goal

### ISSUE THREAD

**Issue by sbozturk** [HarambeSoft/harambe-web-site#14]
Our aim is help people who is undecided. So they can ask their problem to others.

**Comment by gizemfitoz** [comment]
or people can share their opinions to undecided people

bunun gibi bir şeyler de eklenebilir belki ikinci cümlene

**Comment by alperenkirimer** [comment]
we aim to provide social environments where people can help each other by sharing their opinions on the questions asked by people nearby

**Comment by sbozturk** [comment]
Proje dosyasında goal dosyasını görmedim. Pr oluşturup amacı ekledim.
