### ISSUE TITLE
Üst menü içeriği

### ISSUE THREAD

**Issue by isamert** [HarambeSoft/harambe-web-site#2]
Üst menü içeriği doldurulacak. Aklınızdan geçenleri yazın/düzenleyin.

**Comment by sbozturk** [comment]
Üst menüdeki çoğu şey gereksiz geldi. Proje Hakkında, Kişiler, Projenin Aşamaları tarzı 3 başlık olsa işimizi görmez mi?

**Comment by isamert** [comment]
Onlar zaten templateden kalan şeyler.
