### ISSUE TITLE
Ortadaki sunumlar

### ISSUE THREAD

**Issue by isamert** [HarambeSoft/harambe-web-site#3]
Ortadaki sunumların yerine koyulacak resim bulunacak/anlamlı şeylerle doldurulacak.

**Comment by alperenkirimer** [comment]
harambe software yazısı atmıştım o işe yaramaz mı

**Comment by isamert** [comment]
O tam oturmuyor oraya, bi de manzara veya ofis ortamı gibi resimler lazım. Üzerine de şöyle `We make apps for living.`  tarzı bi şeyler yazacağız gibisinden düşün.

**Comment by keremcodes** [comment]
Sunumlardan birine mühendislik fakültesine veya Anadolu Üniversite'sine ait bir resim koyabiliriz.

**Comment by isamert** [comment]
Sonuncu öyle bi placeholder olarak kaldı da yine de işe yarar.
