### ISSUE TITLE
Sayfa içeriği

### ISSUE THREAD

**Issue by isamert** [HarambeSoft/harambe-web-site#4]
Sayfadaki anlamsız yazıların yerini anlamlı şeylerle doldurmak gerek.

**Comment by keremcodes** [comment]
Üç sütundan birinin başlığını "Our goal" yapalım. Altına da

> Our goal is to develop lightweight and useful mobile applications.
> We are working in colloboration with our team of nine engineers.
> For now we are developing for Android devices. 

yazalım.

**Comment by keremcodes** [comment]
Üç sütundan ikincisini de "Our Projects" yapalım. Altına da 

> We are making a project for Software Engineering lecture at Anadolu University.
> We are sharing ideas about project and making plans.

yazalım.

**Comment by isamert** [comment]
Üçüncü de benden gelsin:

> Free & Open Source
> We respect your freedom. As a result of this we are making our applications free (as in freedom).  We offer best solutions for the community. Harambe Software is a company that you can trust.
